/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import model.Model;
import model.UsersTable;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author parra.raul
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public View() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogUsers = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jLabelUsuariosCont = new javax.swing.JLabel();
        jButtonSaveUsers = new javax.swing.JButton();
        jButtonBackUsers = new javax.swing.JButton();
        jButtonBestUser = new javax.swing.JButton();
        jDialogProducts = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jButtonBackProducts = new javax.swing.JButton();
        jButtonSaveProducts = new javax.swing.JButton();
        jLabelProductsCont = new javax.swing.JLabel();
        jDialogPurchases = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBiling = new javax.swing.JTable();
        jButtonBackPurchases = new javax.swing.JButton();
        jButtonBESTUSERP = new javax.swing.JButton();
        jDialogBiling = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxFacturation = new javax.swing.JComboBox<>();
        jButtonOK = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaFacturation = new javax.swing.JTextArea();
        jButtonBACKFACTURATION = new javax.swing.JButton();
        jButtonSaveFact = new javax.swing.JButton();
        jDialogBESTUSER = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaBestUserB = new javax.swing.JTextArea();
        jButtonBACKUSER = new javax.swing.JButton();
        jDialogBookings = new javax.swing.JDialog();
        jButtonBackBookings = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableBookings = new javax.swing.JTable();
        jLabelBookings = new javax.swing.JLabel();
        jButtonSaveBookings = new javax.swing.JButton();
        jDialogGraphicsGeneral = new javax.swing.JDialog();
        jButtonGraphicView = new javax.swing.JButton();
        jButtonPieChart = new javax.swing.JButton();
        jButtonBackView = new javax.swing.JButton();
        jButtonAnotherGraphic = new javax.swing.JButton();
        jLabelTextoPrincipal = new javax.swing.JLabel();
        jButtonUsers = new javax.swing.JButton();
        jButtonProducts = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonPurchases = new javax.swing.JButton();
        jButtonBiling = new javax.swing.JButton();
        jButtonBOOKINGS = new javax.swing.JButton();
        jButtonGraphicsGeneral = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("USERS");

        jScrollPane1.setViewportView(jTableUsers);

        jButtonSaveUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSaveUsers.setText("SAVE");
        jButtonSaveUsers.setActionCommand("SAVE_USERS");

        jButtonBackUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBackUsers.setText("BACK");
        jButtonBackUsers.setActionCommand("BACK_USERS");

        jButtonBestUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBestUser.setText("BEST USER");
        jButtonBestUser.setActionCommand("BESTUSER");

        javax.swing.GroupLayout jDialogUsersLayout = new javax.swing.GroupLayout(jDialogUsers.getContentPane());
        jDialogUsers.getContentPane().setLayout(jDialogUsersLayout);
        jDialogUsersLayout.setHorizontalGroup(
            jDialogUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(jDialogUsersLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDialogUsersLayout.createSequentialGroup()
                        .addComponent(jLabelUsuariosCont, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSaveUsers))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogUsersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBestUser)
                        .addGap(109, 109, 109)
                        .addComponent(jButtonBackUsers)))
                .addContainerGap())
        );
        jDialogUsersLayout.setVerticalGroup(
            jDialogUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSaveUsers)
                    .addGroup(jDialogUsersLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUsuariosCont, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackUsers)
                    .addComponent(jButtonBestUser))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PRODUCTS");

        jScrollPane2.setViewportView(jTableProducts);

        jButtonBackProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBackProducts.setText("BACK");
        jButtonBackProducts.setActionCommand("BACK_PRODUCTS");

        jButtonSaveProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSaveProducts.setText("SAVE");
        jButtonSaveProducts.setActionCommand("SAVE_PRODUCTS");
        jButtonSaveProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogProductsLayout = new javax.swing.GroupLayout(jDialogProducts.getContentPane());
        jDialogProducts.getContentPane().setLayout(jDialogProductsLayout);
        jDialogProductsLayout.setHorizontalGroup(
            jDialogProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogProductsLayout.createSequentialGroup()
                        .addGroup(jDialogProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(jDialogProductsLayout.createSequentialGroup()
                        .addComponent(jLabelProductsCont, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialogProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSaveProducts)
                            .addComponent(jButtonBackProducts))
                        .addGap(25, 25, 25))))
        );
        jDialogProductsLayout.setVerticalGroup(
            jDialogProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveProducts)
                    .addComponent(jLabelProductsCont, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBackProducts))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PURCHASES");

        jScrollPane3.setViewportView(jTableBiling);

        jButtonBackPurchases.setText("BACK");
        jButtonBackPurchases.setActionCommand("BACK_PURCHASES");

        jButtonBESTUSERP.setText("BEST USER ");
        jButtonBESTUSERP.setActionCommand("BESTUSERP");

        javax.swing.GroupLayout jDialogPurchasesLayout = new javax.swing.GroupLayout(jDialogPurchases.getContentPane());
        jDialogPurchases.getContentPane().setLayout(jDialogPurchasesLayout);
        jDialogPurchasesLayout.setHorizontalGroup(
            jDialogPurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPurchasesLayout.createSequentialGroup()
                .addGroup(jDialogPurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogPurchasesLayout.createSequentialGroup()
                        .addGroup(jDialogPurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogPurchasesLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogPurchasesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPurchasesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBESTUSERP)
                        .addGap(144, 144, 144)
                        .addComponent(jButtonBackPurchases)))
                .addContainerGap())
        );
        jDialogPurchasesLayout.setVerticalGroup(
            jDialogPurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPurchasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogPurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackPurchases)
                    .addComponent(jButtonBESTUSERP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("FACTURATION");

        jComboBoxFacturation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bookings Facturation Annual", "Purchase Facturation Annual", "Total Facturation Annual" }));
        jComboBoxFacturation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFacturationActionPerformed(evt);
            }
        });

        jButtonOK.setText("OK");

        jTextAreaFacturation.setColumns(20);
        jTextAreaFacturation.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextAreaFacturation.setRows(5);
        jScrollPane4.setViewportView(jTextAreaFacturation);

        jButtonBACKFACTURATION.setText("BACK");
        jButtonBACKFACTURATION.setActionCommand("BACKFACTURATION");

        jButtonSaveFact.setText("SAVE");
        jButtonSaveFact.setActionCommand("SAVE_FACT");

        javax.swing.GroupLayout jDialogBilingLayout = new javax.swing.GroupLayout(jDialogBiling.getContentPane());
        jDialogBiling.getContentPane().setLayout(jDialogBilingLayout);
        jDialogBilingLayout.setHorizontalGroup(
            jDialogBilingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBilingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogBilingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogBilingLayout.createSequentialGroup()
                        .addComponent(jButtonBACKFACTURATION)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOK))
                    .addGroup(jDialogBilingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxFacturation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSaveFact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jDialogBilingLayout.setVerticalGroup(
            jDialogBilingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBilingLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jDialogBilingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxFacturation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jDialogBilingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonBACKFACTURATION))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSaveFact)
                .addGap(36, 36, 36))
        );

        jTextAreaBestUserB.setColumns(20);
        jTextAreaBestUserB.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextAreaBestUserB.setRows(5);
        jScrollPane5.setViewportView(jTextAreaBestUserB);

        jButtonBACKUSER.setText("BACK");
        jButtonBACKUSER.setActionCommand("BACKUSER");

        javax.swing.GroupLayout jDialogBESTUSERLayout = new javax.swing.GroupLayout(jDialogBESTUSER.getContentPane());
        jDialogBESTUSER.getContentPane().setLayout(jDialogBESTUSERLayout);
        jDialogBESTUSERLayout.setHorizontalGroup(
            jDialogBESTUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBESTUSERLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBACKUSER)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jDialogBESTUSERLayout.setVerticalGroup(
            jDialogBESTUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBESTUSERLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDialogBESTUSERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBACKUSER)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jButtonBackBookings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBackBookings.setText("BACK");
        jButtonBackBookings.setActionCommand("BACKBOOKINGS");

        jTableBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTableBookings);

        jLabelBookings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBookings.setText("BOOKINGS");

        jButtonSaveBookings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSaveBookings.setText("SAVE");
        jButtonSaveBookings.setToolTipText("");
        jButtonSaveBookings.setActionCommand("SAVE_Bookings");

        javax.swing.GroupLayout jDialogBookingsLayout = new javax.swing.GroupLayout(jDialogBookings.getContentPane());
        jDialogBookings.getContentPane().setLayout(jDialogBookingsLayout);
        jDialogBookingsLayout.setHorizontalGroup(
            jDialogBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogBookingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogBookingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSaveBookings)
                    .addComponent(jButtonBackBookings))
                .addGap(24, 24, 24))
        );
        jDialogBookingsLayout.setVerticalGroup(
            jDialogBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogBookingsLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabelBookings)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSaveBookings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBackBookings)
                .addGap(18, 18, 18))
        );

        jButtonGraphicView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGraphicView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BarChart.jpg"))); // NOI18N
        jButtonGraphicView.setText("Graphic Bookings & Purchases");
        jButtonGraphicView.setToolTipText("");
        jButtonGraphicView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraphicViewActionPerformed(evt);
            }
        });

        jButtonPieChart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPieChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/piechart.jpg"))); // NOI18N
        jButtonPieChart.setText("Graphic Pie Chart");
        jButtonPieChart.setActionCommand("GraphicPieChart");
        jButtonPieChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPieChartActionPerformed(evt);
            }
        });

        jButtonBackView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBackView.setText("BACK");
        jButtonBackView.setActionCommand("BACKVIEW");

        jButtonAnotherGraphic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAnotherGraphic.setText("Another");
        jButtonAnotherGraphic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnotherGraphicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogGraphicsGeneralLayout = new javax.swing.GroupLayout(jDialogGraphicsGeneral.getContentPane());
        jDialogGraphicsGeneral.getContentPane().setLayout(jDialogGraphicsGeneralLayout);
        jDialogGraphicsGeneralLayout.setHorizontalGroup(
            jDialogGraphicsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGraphicsGeneralLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDialogGraphicsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogGraphicsGeneralLayout.createSequentialGroup()
                        .addComponent(jButtonAnotherGraphic, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBackView)
                        .addGap(25, 25, 25))
                    .addGroup(jDialogGraphicsGeneralLayout.createSequentialGroup()
                        .addGroup(jDialogGraphicsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGraphicView)
                            .addComponent(jButtonPieChart))
                        .addContainerGap(135, Short.MAX_VALUE))))
        );
        jDialogGraphicsGeneralLayout.setVerticalGroup(
            jDialogGraphicsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGraphicsGeneralLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButtonGraphicView)
                .addGap(34, 34, 34)
                .addComponent(jButtonPieChart)
                .addGroup(jDialogGraphicsGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogGraphicsGeneralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBackView)
                        .addGap(34, 34, 34))
                    .addGroup(jDialogGraphicsGeneralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnotherGraphic)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTextoPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTextoPrincipal.setText("DIY MANAGMENT");

        jButtonUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUsers.setText("USERS");
        jButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsersActionPerformed(evt);
            }
        });

        jButtonProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonProducts.setText("PRODUCTS");

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonPurchases.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPurchases.setText("PURCHASES");

        jButtonBiling.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBiling.setText("FACTURATION");
        jButtonBiling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBilingActionPerformed(evt);
            }
        });

        jButtonBOOKINGS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario-marketing-2019-bicubic.jpg"))); // NOI18N
        jButtonBOOKINGS.setActionCommand("BOOKINGS");
        jButtonBOOKINGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBOOKINGSActionPerformed(evt);
            }
        });

        jButtonGraphicsGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGraphicsGeneral.setText("GRAPHICS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTextoPrincipal)
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPurchases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBOOKINGS, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBiling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonGraphicsGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTextoPrincipal)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUsers)
                            .addComponent(jButtonProducts))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPurchases)
                            .addComponent(jButtonBiling)))
                    .addComponent(jButtonBOOKINGS, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonGraphicsGeneral)
                .addGap(14, 14, 14)
                .addComponent(jButtonExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsersActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonSaveProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveProductsActionPerformed

    private void jComboBoxFacturationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFacturationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFacturationActionPerformed

    private void jButtonBilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBilingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBilingActionPerformed

    private void jButtonBOOKINGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBOOKINGSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBOOKINGSActionPerformed

    private void jButtonGraphicViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraphicViewActionPerformed
        // TODO add your handling code here:
        double cantidad1 = Model.bookingsFacturation();
        double cantidad2 = Model.purchaseFacturation();

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(cantidad1, "Bookings Facturation", "");
            ds.addValue(cantidad2, "Purchase Facturation", "");

            JFreeChart jf;
            jf = ChartFactory.createBarChart3D("Facturation", "Comparison between Bookings Facturation and Purchase Facturation", "EARNED MONEY", ds, PlotOrientation.HORIZONTAL, true, true, true);
            ChartFrame f = new ChartFrame("Graphic", jf);
            f.setSize(1000, 600);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGraphicViewActionPerformed

    private void jButtonPieChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPieChartActionPerformed
        // TODO add your handling code here:
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("January", Model.bookingsMonthD(1));
        pieDataset.setValue("February", Model.bookingsMonthD(2));
        pieDataset.setValue("March", Model.bookingsMonthD(3));
        pieDataset.setValue("April", Model.bookingsMonthD(4));
        pieDataset.setValue("May", Model.bookingsMonthD(5));
        pieDataset.setValue("June", Model.bookingsMonthD(6));
        pieDataset.setValue("July", Model.bookingsMonthD(7));
        pieDataset.setValue("August", Model.bookingsMonthD(8));
        pieDataset.setValue("September", Model.bookingsMonthD(9));
        pieDataset.setValue("October", Model.bookingsMonthD(10));
        pieDataset.setValue("November", Model.bookingsMonthD(11));
        pieDataset.setValue("December", Model.bookingsMonthD(12));
        JFreeChart piechart = ChartFactory.createPieChart("Pie Chart", pieDataset, true, true, true);
        PiePlot P = (PiePlot) piechart.getPlot();
//        P.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Pie Chart", piechart);
        frame.setVisible(true);
        frame.setSize(750, 530);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonPieChartActionPerformed

    private void jButtonAnotherGraphicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnotherGraphicActionPerformed
        // TODO add your handling code here:
        double cantidad1 = Model.bookingsMonthD(1);
        double cantidad2 = Model.bookingsMonthD(2);
        double cantidad3 = Model.bookingsMonthD(3);
        double cantidad4 = Model.bookingsMonthD(4);
        double cantidad5 = Model.bookingsMonthD(5);
        double cantidad6 = Model.bookingsMonthD(6);
        double cantidad7 = Model.bookingsMonthD(7);
        double cantidad8 = Model.bookingsMonthD(8);
        double cantidad9 = Model.bookingsMonthD(9);
        double cantidad10 = Model.bookingsMonthD(10);
        double cantidad11 = Model.bookingsMonthD(11);
        double cantidad12 = Model.bookingsMonthD(12);

        try {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ds.addValue(cantidad1, "January", "");
            ds.addValue(cantidad2, "February", "");
            ds.addValue(cantidad3, "March", "");
            ds.addValue(cantidad4, "April", "");
            ds.addValue(cantidad5, "May", "");
            ds.addValue(cantidad6, "June", "");
            ds.addValue(cantidad7, "July", "");
            ds.addValue(cantidad8, "August", "");
            ds.addValue(cantidad9, "September", "");
            ds.addValue(cantidad10, "October", "");
            ds.addValue(cantidad11, "November", "");
            ds.addValue(cantidad12, "December", "");
            

            JFreeChart jf;
            jf = ChartFactory.createBarChart3D("Bookings", "Comparison between Bookings per Month", "EARNED MONEY", ds, PlotOrientation.VERTICAL, true, true, true);
            ChartFrame f = new ChartFrame("Graphic", jf);
            f.setSize(1000, 600);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAnotherGraphicActionPerformed

    public static View viewaSortuBistaratu() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
            }
        });
        return v;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAnotherGraphic;
    public javax.swing.JButton jButtonBACKFACTURATION;
    public javax.swing.JButton jButtonBACKUSER;
    public javax.swing.JButton jButtonBESTUSERP;
    public javax.swing.JButton jButtonBOOKINGS;
    public javax.swing.JButton jButtonBackBookings;
    public javax.swing.JButton jButtonBackProducts;
    public javax.swing.JButton jButtonBackPurchases;
    public javax.swing.JButton jButtonBackUsers;
    public javax.swing.JButton jButtonBackView;
    public javax.swing.JButton jButtonBestUser;
    public javax.swing.JButton jButtonBiling;
    public javax.swing.JButton jButtonExit;
    public javax.swing.JButton jButtonGraphicView;
    public javax.swing.JButton jButtonGraphicsGeneral;
    public javax.swing.JButton jButtonOK;
    public javax.swing.JButton jButtonPieChart;
    public javax.swing.JButton jButtonProducts;
    public javax.swing.JButton jButtonPurchases;
    public javax.swing.JButton jButtonSaveBookings;
    public javax.swing.JButton jButtonSaveFact;
    public javax.swing.JButton jButtonSaveProducts;
    public javax.swing.JButton jButtonSaveUsers;
    public javax.swing.JButton jButtonUsers;
    public javax.swing.JComboBox<String> jComboBoxFacturation;
    public javax.swing.JDialog jDialogBESTUSER;
    public javax.swing.JDialog jDialogBiling;
    public javax.swing.JDialog jDialogBookings;
    public javax.swing.JDialog jDialogGraphicsGeneral;
    public javax.swing.JDialog jDialogProducts;
    public javax.swing.JDialog jDialogPurchases;
    public javax.swing.JDialog jDialogUsers;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabelBookings;
    public javax.swing.JLabel jLabelProductsCont;
    private javax.swing.JLabel jLabelTextoPrincipal;
    public javax.swing.JLabel jLabelUsuariosCont;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable jTableBiling;
    public javax.swing.JTable jTableBookings;
    public javax.swing.JTable jTableProducts;
    public javax.swing.JTable jTableUsers;
    public javax.swing.JTextArea jTextAreaBestUserB;
    public javax.swing.JTextArea jTextAreaFacturation;
    // End of variables declaration//GEN-END:variables
}
